remote_theme: pages-themes/slate@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: How To Make A Layout Website
description: A sample with multiple pages, foratted text, tables, and images
show_downloads: false
google_analytics: G-HowToMakeALayoutWebsite
